### ISSUE TITLE
Crash on world load.

### ISSUE THREAD

**Issue by 63502** [KryptonCaptain/ThaumicUtilities#1]
I got a crash related to the fireproof runic shield thing when I tried to open a test world.

[Crash Log](https://gist.github.com/63502/c7fddc095b8991d9bba40e41f7b71326)

**Comment by KryptonCaptain** [comment]
Every time I try and fix this, it breaks a different way

**Comment by 63502** [comment]
Oh god, one of those huh...

**Comment by KryptonCaptain** [comment]
This feature has given me nothing but trouble

**Comment by KryptonCaptain** [comment]
Closing because fireproof runic has been removed.
